// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"user-management/internal/config"
	"user-management/internal/infrastructure/web"
)

// Injectors from wire.go:

func InitializeServer() (*web.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	server := web.NewServer(configConfig)
	return server, nil
}
